language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

sudo: false

before_script:
  - composer install -n --dev --prefer-source

script: vendor/bin/phpcs --standard=PSR2 src && vendor/bin/phpunit --coverage-text
